packages/ui/src/components/surfaces/accordion/details/index.tsx
packages/ui/src/components/surfaces/accordion/index.tsx
packages/ui/src/components/surfaces/accordion/summary/index.tsx
packages/ui/src/components/surfaces/card/index.tsx
packages/ui/src/components/surfaces/card/title/index.tsx

Minor tweaks for the `card` and `accordions` components.

Minor UI components fixes

---

packages/frontend/src/components/connect-wallet/popovers/preferences/index.tsx
packages/react/src/contexts/preferences/index.tsx

Persist the interface settings preferences on local storage.

Persist theme preferences

---

packages/ui/src/components/input/tags/index.stories.tsx
packages/ui/src/components/input/tags/index.tsx

Add a button to the tags input for a more intuitive ux (also on mobile it wasn't possible to add tags).

Add button to tags input

---

packages/frontend/src/components/ui/navbar/popovers/preferences/index.tsx
packages/frontend/src/i18n/resources/en.ts
packages/shared-state/src/reducers/preferences/reducer/index.ts
packages/ui/src/components/input/switch/index.tsx

Dark theme is not ready right now and probably won't be at launch. This PR disables dark theme and adds a popover to make it clear that it's coming soon.

Temporarily disable dark theme

---

packages/ui/src/components/input/checkbox/index.tsx
packages/ui/src/components/input/radio/index.tsx

Needed for these changes https://github.com/carrot-kpi/reality-eth-v3-oracle-template/pull/13.

Checkbox popover

---

packages/frontend/src/components/connect-wallet/index.tsx
packages/frontend/src/components/ui/empty/index.tsx
packages/frontend/src/components/ui/navbar/index.tsx
packages/frontend/src/i18n/resources/en.ts

In modal mode (i.e. when consuming a template) network switching is now disabled.

Disabled network switching while in modal mode

---

packages/frontend/src/components/connect-wallet/popovers/account/transaction/index.tsx
packages/frontend/src/utils/explorers.ts

Fixes https://github.com/carrot-kpi/erc20-kpi-token-template/issues/65.

Broken tx explorer link

---

packages/frontend/src/i18n/resources/en.ts
packages/frontend/src/pages/campaigns/index.tsx
packages/frontend/src/pages/campaigns/top-nav/index.tsx
packages/frontend/src/utils/kpi-tokens.ts

closes #187 
Related to this PR: #189

feat: add campaigns sorting by date

---

packages/frontend/src/i18n/resources/en.ts
packages/frontend/src/pages/campaigns/index.tsx
packages/frontend/src/pages/campaigns/top-nav/index.tsx
packages/frontend/src/utils/kpi-tokens.ts

implement campaign state filtering

---

packages/frontend/src/assets/connectors/metamask.svg

Fixes https://github.com/carrot-kpi/erc20-kpi-token-template/issues/75.

Change metamask connector svg viewbox

---

packages/frontend/src/pages/campaigns/index.tsx

Fixes https://github.com/carrot-kpi/erc20-kpi-token-template/issues/74.

Use flexbox instead of grid

---

packages/frontend/src/connectors/frame/index.ts

Closes https://github.com/carrot-kpi/erc20-kpi-token-template/issues/67

fix(frontend): only show frame connector when frame is actually available

---

packages/frontend/src/components/connect-wallet/index.tsx
packages/frontend/src/components/connect-wallet/popovers/account/index.tsx
packages/frontend/src/components/ui/navbar/index.tsx
packages/frontend/src/components/ui/navbar/popovers/preferences/index.tsx
packages/frontend/src/components/ui/navbar/vertical-layout/index.tsx
packages/frontend/src/pages/campaigns/side-filters/index.tsx

Improvements for the navbar components on mobile.

Mobile navbar

---

packages/frontend/src/components/fullscreen-modal/index.tsx
packages/frontend/src/pages/home/hero/index.tsx
packages/frontend/src/state/index.ts
packages/frontend/src/state/reducers/modals/actions/index.ts
packages/frontend/src/state/reducers/modals/index.ts
packages/frontend/src/state/reducers/modals/reducer/index.ts
packages/frontend/src/state/reducers/modals/types/index.ts
packages/frontend/src/utils/state.ts

**summary**
The video should autoplay on mute. 
If a modal is open, it should pause and when the modal is closed it should play again.
---
**Test flow**
1. Go to landing
2. Check if the video is playing on mute
3. open a modal (video should pause)
4. close modal (video should play)

fix: make video pause when opening modal, also remove autoplay

---

.changeset/rude-weeks-change.md
packages/react/src/core-provider.tsx

* fix(react): increase default provider timeout to 1 minute
* chore: add changeset
---------

fix: providers timeout (#358)

---

.changeset/green-beans-move.md
packages/frontend/src/bootstrap.tsx
packages/frontend/src/components/authenticate/index.tsx
packages/frontend/src/constants/index.ts
packages/frontend/src/hooks/useBlacklistedTokens.ts
packages/frontend/src/hooks/useFeaturedKPITokens.ts
packages/frontend/src/pages/app/index.tsx
packages/frontend/src/pages/home/hero/index.tsx
packages/react/src/hooks/useDecentralizedStorageUploader.ts
packages/sdk/package.json
packages/sdk/rollup.config.mjs
packages/sdk/src/commons.ts
packages/sdk/src/utils/index.ts
packages/sdk/src/utils/services.ts
packages/shared-state/src/reducers/preferences/reducer/index.ts
packages/ui/stories/erc20-token-picker.stories.tsx

* feat: adapt packages to work with separate staging/prod services
* chore: add changeset
* fix(frontend): enable mainnets only in prod
---------

feat: handle different staging/prod clusters/services (#395)

---

.changeset/chilled-oranges-carry.md
packages/frontend/package.json

* chore(frontend): fix package.json
* chore: add changeset
---------

chore(frontend): fix package.json (#402)

---

.changeset/neat-pens-lick.md
packages/frontend/src/components/permissioned/index.tsx
packages/frontend/src/i18n/resources/en.ts
packages/frontend/src/icons/error.tsx
packages/frontend/src/pages/campaigns/index.tsx
packages/frontend/src/pages/create-with-template-id/index.tsx

feat(frontend): add permissioned warning when creating campaigns

---

.changeset/rude-penguins-tan.md
.changeset/shaggy-spoons-hammer.md
packages/ui/src/components/date-time-input/picker/index.tsx
packages/ui/src/components/popover.tsx

* fix(ui): fix popover positioning on open
* fix(ui): avoid inconsistent min and max date log firing in the wrong scenarios
---------

fix(ui): fix popover positioning on open (#499)

---

.github/workflows/ci.yml
.gitignore
package.json
packages/frontend/CONTRIBUTING.md
packages/frontend/e2e/fixtures.ts
packages/frontend/e2e/tests/connect-wallet.test.ts
packages/frontend/e2e/tests/home-page.test.ts
packages/frontend/package.json
packages/frontend/playwright.config.ts
packages/frontend/src/components/connect-wallet/index.tsx
packages/frontend/src/components/connect-wallet/popovers/account/index.tsx
packages/frontend/src/components/connect-wallet/popovers/connect.tsx
packages/frontend/src/components/connect-wallet/popovers/networks.tsx
turbo.json
yarn.lock

Courtesy and credit: @MilanVojnovic95

feat(frontend): add e2e tests setup with playwright and synpress

---

packages/frontend/src/components/connect-wallet/index.tsx
packages/frontend/src/components/create-campaign-button.tsx
packages/frontend/src/components/permissioned.tsx
packages/frontend/src/components/staging-mode-banner.tsx
packages/frontend/src/components/ui/empty.tsx
packages/frontend/src/components/ui/footer.tsx
packages/frontend/src/components/ui/kpi-token-card.tsx
packages/frontend/src/components/ui/navbar/index.tsx
packages/frontend/src/components/ui/navbar/popovers/preferences.tsx
packages/frontend/src/components/ui/template-card.tsx
packages/frontend/src/components/wallet-disconnected.tsx
packages/frontend/src/pages/campaigns/index.tsx
packages/frontend/src/pages/campaigns/top-nav/index.tsx
packages/frontend/src/pages/home/hero.tsx
packages/frontend/src/pages/home/latest-campaigns-section.tsx
packages/frontend/src/pages/home/templates-section.tsx
yarn.lock

- adding selectors for smoke test checks

feat(qa): adding selectors for smoke test

---

.changeset/empty-peaches-hear.md
packages/ui/src/components/markdown-input/index.tsx
packages/ui/src/components/multi-step-cards/next-button/index.tsx

* feat(ui): adapt next button to new design
* fix(ui): use font mono in mardkdown input
* docs: add changeset

Trigger release

---

.changeset/lemon-experts-do.md
packages/ui/src/components/card/index.tsx
packages/ui/src/components/date-input/index.tsx
packages/ui/src/components/date-input/picker/index.tsx
packages/ui/src/components/date-time-input/index.tsx
packages/ui/src/components/date-time-input/picker/index.tsx
packages/ui/src/components/erc20-token-picker/index.tsx
packages/ui/src/components/erc20-token-picker/manage-lists/index.tsx
packages/ui/src/components/erc20-token-picker/search/index.tsx
packages/ui/src/components/erc20-token-picker/search/row/index.tsx
packages/ui/src/components/modal.tsx
packages/ui/src/components/select.tsx
packages/ui/src/components/tags-input.tsx

Add optional dedicated `dataTestIds` props for complex components for better testing purposes.

Dedicated data test ids

---

.changeset/heavy-tools-explode.md
.changeset/two-swans-pretend.md
.changeset/wet-parents-eat.md
packages/frontend/package.json
packages/frontend/shared-dependencies.json
packages/frontend/src/components/chain-select/chain-select.tsx
packages/frontend/src/components/chain-select/networks-popover.tsx
packages/frontend/src/components/connect-wallet/actions/types/transactions/transaction.tsx
packages/frontend/src/constants.ts
packages/frontend/src/library-mode-entrypoint.tsx
packages/frontend/src/react-app-env.d.ts
packages/frontend/src/shared-entrypoint.tsx
packages/frontend/src/standalone-entrypoint.tsx
packages/react/src/hooks/useWagmiPassiveHook.ts
packages/ui/package.json
yarn.lock

* refactor(frontend): remove augmented wagmi chains
* fix(ui): add react-query to peer dependencies
* fix(react): adapt wagmi passive hook to new version
* docs: add changeset
* chore: address comments
---------

refactor: wagmi config (#590)

---

.changeset/sharp-ducks-admire.md
packages/frontend/src/components/campaign-creation-form.tsx
packages/frontend/src/i18n/resources/en.ts
packages/frontend/src/library-mode-entrypoint.tsx
packages/frontend/src/pages/app.tsx
packages/frontend/src/pages/home/index.tsx
packages/frontend/src/shared-entrypoint.tsx
packages/frontend/src/standalone-entrypoint.tsx
packages/frontend/src/utils/draft.ts

feat(fronted): add unsaved changes check on creation form
